### ISSUE TITLE
vendordata2.json is not auto loaded by cloud-init

### ISSUE THREAD

**Issue by IamFive** [mikalstill/vendordata#1]
thank you for sharing this sample vendordata metadata service project.

When I try to setup a test env for load customer vendordata, but it ends with vendor_data2.json is not loaded.
Dynamic vendordata is available through "curl http://169.254.169.254/openstack/2018-08-27/vendor_data2.json" in the instance, but could-init seems never load it.

And  i do not see how it works, from the source code: https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/helpers/openstack.py#L230-L255, it seems vendor_data2.json is never loaded by OpenStack datasource.

So, should i write a script load vendor_data2.json myself? Or, i need to update some configuration to make cloud-init load it?
Thanks in advance.

**Comment by srelf-eschercloud** [comment]
Generally I think it is expected that you should load it yourself. You might be able to change the cloud-init config to load it automaticity.

**Comment by mikalstill** [comment]
Vendor data was never intended to be automatically loaded by cloud-init -- its there for your customized tooling to load once the instance has been bootstrapped by cloud-init.
